before_install <- function() {
    ## Build various bits of autogenerated code
    install.packages(c("devtools", "roxygen2", "testthat", "rmarkdown", "pkgdown"))
    devtools::install_deps(
        dependencies = c("Depends", "Imports", "LinkingTo"),
        quiet = FALSE, upgrade = TRUE
    )
    roxygen2::roxygenize()
    Rcpp::compileAttributes(verbose = TRUE)
    devtools::document()

    ## GitHash as used by moma:::moma_git_hash()
    dir.create("inst", showWarnings = FALSE)
    writeLines(system("git rev-parse HEAD", intern = TRUE), "inst/GIT.HASH")

    ## Write custom dictionary words
    dir.create(".aspell", showWarnings = FALSE)
    saveRDS(c("ArXiv"), ".aspell/moma.rds")
}

after_success <- function() {
    devtools::install(
        reload = TRUE, quick = TRUE, quiet = FALSE, upgrade = FALSE,
        auth_token = Sys.getenv("GITHUB_TOKEN") %||% devtools::github_pat(FALSE)
    )

    rmarkdown::render("README.Rmd", clean = FALSE)
    unlink("README.knit.md", force = TRUE)
    unlink("README.utf8.md", force = TRUE)

    ## Build pkgdown site
    pkgdown::build_site()

    unlink(Sys.glob("MoMA.Rcheck"), recursive = TRUE, force = TRUE)
    unlink(Sys.glob("MoMA_*.tar.gz"), recursive = TRUE, force = TRUE)
    file.rename(".gitignore.deploy", ".gitignore")
    unlink(Sys.glob("src/*o"), force = TRUE)
}
