before_install <- function() {
    ## Build various bits of autogenerated code
    install.packages(c("devtools", "roxygen2", "testthat", "rmarkdown"))
    devtools::install_deps(
        dependencies = c("Depends", "Imports", "LinkingTo"),
        quiet = FALSE, upgrade = TRUE
    )
    roxygen2::roxygenize()
    Rcpp::compileAttributes(verbose = TRUE)
    devtools::document()
    shinytest::installDependencies()

    ## GitHash as used by moma:::moma_git_hash()
    dir.create("inst", showWarnings = FALSE)
    writeLines(system("git rev-parse HEAD", intern = TRUE), "inst/GIT.HASH")

    ## Write custom dictionary words
    dir.create(".aspell", showWarnings = FALSE)
    saveRDS(c("ArXiv"), ".aspell/moma.rds")
}

after_success <- function() {
    devtools::install()
    rmarkdown::render("README.Rmd")
    unlink(Sys.glob("moma.Rcheck"), recursive = TRUE, force = TRUE)
    unlink(Sys.glob("moma*.tar.gz"), recursive = TRUE, force = TRUE)
    file.rename(".gitignore.deploy", ".gitignore")
    unlink(Sys.glob("src/*o"), force = TRUE)
}
