# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_moma_multi_rank <- function(X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, rank = 1L) {
    .Call('_MoMA_cpp_moma_multi_rank', PACKAGE = 'MoMA', X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, rank)
}

cpp_moma_grid_search <- function(X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, rank = 1L) {
    .Call('_MoMA_cpp_moma_grid_search', PACKAGE = 'MoMA', X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, rank)
}

cpp_moma_criterion_search <- function(X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, rank = 1L) {
    .Call('_MoMA_cpp_moma_criterion_search', PACKAGE = 'MoMA', X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, rank)
}

cpp_multirank_BIC_grid_search <- function(X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, deflation_scheme = 1L, select_scheme_alpha_u = 0L, select_scheme_alpha_v = 0L, select_scheme_lambda_u = 0L, select_scheme_lambda_v = 0L, max_bic_iter = 5L, rank = 1L) {
    .Call('_MoMA_cpp_multirank_BIC_grid_search', PACKAGE = 'MoMA', X, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, deflation_scheme, select_scheme_alpha_u, select_scheme_alpha_v, select_scheme_lambda_u, select_scheme_lambda_v, max_bic_iter, rank)
}

cca <- function(X, Y, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, deflation_scheme, select_scheme_alpha_u = 0L, select_scheme_alpha_v = 0L, select_scheme_lambda_u = 0L, select_scheme_lambda_v = 0L, max_bic_iter = 5L, rank = 1L) {
    .Call('_MoMA_cca', PACKAGE = 'MoMA', X, Y, alpha_u, alpha_v, Omega_u, Omega_v, lambda_u, lambda_v, prox_arg_list_u, prox_arg_list_v, EPS, MAX_ITER, EPS_inner, MAX_ITER_inner, solver, deflation_scheme, select_scheme_alpha_u, select_scheme_alpha_v, select_scheme_lambda_u, select_scheme_lambda_v, max_bic_iter, rank)
}

moma_set_logger_level_cpp <- function(level) {
    invisible(.Call('_MoMA_moma_set_logger_level_cpp', PACKAGE = 'MoMA', level))
}

moma_get_logger_level_cpp <- function() {
    .Call('_MoMA_moma_get_logger_level_cpp', PACKAGE = 'MoMA')
}

moma_log_cpp <- function(level, x) {
    invisible(.Call('_MoMA_moma_log_cpp', PACKAGE = 'MoMA', level, x))
}

l1tf_diff_mat <- function(m, k) {
    .Call('_MoMA_l1tf_diff_mat', PACKAGE = 'MoMA', m, k)
}

test_prox_lasso <- function(x, l) {
    .Call('_MoMA_test_prox_lasso', PACKAGE = 'MoMA', x, l)
}

test_prox_nnlasso <- function(x, l) {
    .Call('_MoMA_test_prox_nnlasso', PACKAGE = 'MoMA', x, l)
}

test_prox_scad <- function(x, l, gamma = 3.7) {
    .Call('_MoMA_test_prox_scad', PACKAGE = 'MoMA', x, l, gamma)
}

test_prox_scadvec <- function(x, l, gamma = 3.7) {
    .Call('_MoMA_test_prox_scadvec', PACKAGE = 'MoMA', x, l, gamma)
}

test_prox_nnscad <- function(x, l, gamma = 3.7) {
    .Call('_MoMA_test_prox_nnscad', PACKAGE = 'MoMA', x, l, gamma)
}

test_prox_mcp <- function(x, l, gamma = 4) {
    .Call('_MoMA_test_prox_mcp', PACKAGE = 'MoMA', x, l, gamma)
}

test_prox_mcpvec <- function(x, l, gamma = 4) {
    .Call('_MoMA_test_prox_mcpvec', PACKAGE = 'MoMA', x, l, gamma)
}

test_prox_nnmcp <- function(x, l, gamma = 4) {
    .Call('_MoMA_test_prox_nnmcp', PACKAGE = 'MoMA', x, l, gamma)
}

test_prox_grplasso <- function(x, g, l) {
    .Call('_MoMA_test_prox_grplasso', PACKAGE = 'MoMA', x, g, l)
}

test_prox_nngrplasso <- function(x, g, l) {
    .Call('_MoMA_test_prox_nngrplasso', PACKAGE = 'MoMA', x, g, l)
}

test_prox_fusedlassopath <- function(x, l) {
    .Call('_MoMA_test_prox_fusedlassopath', PACKAGE = 'MoMA', x, l)
}

test_prox_fusedlassodp <- function(x, l) {
    .Call('_MoMA_test_prox_fusedlassodp', PACKAGE = 'MoMA', x, l)
}

test_prox_spfusedlasso <- function(x, l, lambda2) {
    .Call('_MoMA_test_prox_spfusedlasso', PACKAGE = 'MoMA', x, l, lambda2)
}

test_prox_fusion <- function(x, l, w, ADMM, acc, prox_eps = 1e-10) {
    .Call('_MoMA_test_prox_fusion', PACKAGE = 'MoMA', x, l, w, ADMM, acc, prox_eps)
}

test_prox_l1gf <- function(x, l, k = 1L) {
    .Call('_MoMA_test_prox_l1gf', PACKAGE = 'MoMA', x, l, k)
}

test_prox_slope <- function(x, l) {
    .Call('_MoMA_test_prox_slope', PACKAGE = 'MoMA', x, l)
}

test_df_orderedfusion <- function(x) {
    .Call('_MoMA_test_df_orderedfusion', PACKAGE = 'MoMA', x)
}

test_df_spfusedlasso <- function(x) {
    .Call('_MoMA_test_df_spfusedlasso', PACKAGE = 'MoMA', x)
}

test_df_l1gf <- function(x, k = 1L) {
    .Call('_MoMA_test_df_l1gf', PACKAGE = 'MoMA', x, k)
}

test_df_grplasso <- function(x, g) {
    .Call('_MoMA_test_df_grplasso', PACKAGE = 'MoMA', x, g)
}

test_BIC <- function(y, y_est, algorithm_string, i_alpha, i_Omega, i_lambda, prox_arg_list, dim, i_EPS = 1e-6, i_MAX_ITER = 1e+3L) {
    .Call('_MoMA_test_BIC', PACKAGE = 'MoMA', y, y_est, algorithm_string, i_alpha, i_Omega, i_lambda, prox_arg_list, dim, i_EPS, i_MAX_ITER)
}

